# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'qvdm'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu: 
  - name: Projects
    submenu:
      - name: Strata Council Registry
        link: /projects/strata.html
      - name: Crime Prevention
        link: /projects/crime.html
  - name: News
    link: /
  - name: About
    link: /about
  - name: Follow us
    submenu:
      - name: Twitter
        icon: twitter
        link: https://twitter.com/nwdra
      - name: Facebook
        icon: facebook
        link: https://facebook.com/nwdra
        
    
